local ui = require("libyalul")

ui.init()

ui.newMenu("File")
    :appendItem("Open"):onItemClicked(function() print("Open") end)
    :appendItem("Save")
    :appendSeparator()
    :appendCheckItem("Enable"):setItemChecked(true):onItemClicked(
        function(checked)
            print(checked) 
        end)
ui.newMenu("Edit")
    :appendItem("Copy")
    :appendItem("Cut")
    :appendItem("paste")  

local w = ui.newWindow("yalul Control Gallery", 640, 480, true)
    :setMargined(1)
    :onClosing(
        function() 
            ui.quit() 
        end
    ):setChild(ui.newHBox():setPadded(1)
        :append(ui.newGroup("Basic Controls"):setMargined(1)
            :setChild(ui.newVBox():setPadded(1)
                :append(ui.newButton("Button"))
                :append(ui.newCheckbox("Checkbox"):setChecked(true))
                :append(ui.newEntry():setText("Entry"))
                :append(ui.newLabel("Label"))
                :append(ui.newColorButton():setColor(0, 0, 0, 1))
            )
        ):append(ui.newVBox()
            :append(ui.newGroup("Numbers"):setMargined(1)
                :setChild(ui.newVBox():setPadded(1)
                    :append(ui.newSpinbox(0, 100):setValue(50))
                    :append(ui.newSlider(0, 100):setValue(50))
                    :append(ui.newProgressBar(0, 100):setValue(50))
                )
            ):append(ui.newGroup("Lists"):setMargined(1)
                :setChild(ui.newVBox():setPadded(1)
                    :append(ui.newCombobox()
                        :append("Combobox Item 1", "Combobox Item 2", "Combobox Item 3")
                        :setSelected(1))
                    :append(ui.newEditableCombobox()
                        :append("Editable Item 1", "Editable Item 2", "Editable Item 3")
                        :setText("Editable Item 2"))
                    :append(ui.newRadioButtons()
                        :append("Radio Button 1", "Radio Button 2", "Radio Button 3")
                        :setSelected(3))
                )
            ):append(ui.newTab()
                :append("Page 1", ui.newLabel("Welcome"))
                :append("Page 2", ui.newLabel("Wonderful"))
                :append("Page 3", ui.newLabel("Powerful"))
                :setMargined(1, 1)
                :setMargined(2, 1)
                :setMargined(3, 1)
            )
        , true)
    ):show()

ui.main()
