#define YALUL_BUTTON_LIB    "yalul.button"
#define YALUL_LABEL_LIB     "yalul.label"
#define YALUL_CHECKBOX_LIB  "yalul.checkbox"
#define YALUL_WINDOW_LIB    "yalul.window"
#define YALUL_BOX_LIB       "yalul.box"
#define YALUL_ENTRY_LIB     "yalul.entry"
#define YALUL_PROGRESSBAR_LIB   "yalul.progressbar"
#define YALUL_RADIOBUTTONS_LIB  "yalul.radiobuttons"
#define YALUL_COLORBUTTON_LIB   "yalul.colorbutton"
#define YALUL_COMBOBOX_LIB      "yalul.combobox"
#define YALUL_EDITABLECOMBOBOX_LIB     "yalul.editablecombobox"
#define YALUL_SLIDER_LIB    "yalul.slider"
#define YALUL_SPINBOX_LIB   "yalul.spinbox"
#define YALUL_GROUP_LIB     "yalul.group"
#define YALUL_TAB_LIB       "yalul.tab"
#define YALUL_MULTILINEENTRY_LIB       "yalul.multilineentry"
#define YALUL_DATETIMEPICKER_LIB       "yalul.datetimepicker"
#define YALUL_SEPARATOR_LIB "yalul.separator"
#define YALUL_FORM_LIB      "yalul.form"

#define YALUL_MENU_LIB      "yalul.menu"
#define YALUL_MENUS_LIB     "yalul.menus"

#define YALUL_INITED        "yalul.inited"

#define YALUL_ONCLICKED     "onClicked"
#define YALUL_ONCLOSING     "onClosing"
#define YALUL_ONTOGGLED     "onToggled"
#define YALUL_ONCHANGED     "onChanged"
#define YALUL_ONSELECTED    "onSelected"
#define YALUL_ONPOSCHANGED  "onPositionChanged"
#define YALUL_ONSIZECHANGED "onSizeChanged"
